---
title: "Maps"
author: "Janeci Leoni Dewes"
date: "10/24/2020"
output: html_document
---

## Maps packages


```{r}
# Instalar e carregar os pacotes
# install.packages(c("ggplot2", "maps", "mapdata"))
library(ggplot2)
library(maps)
library(mapdata)
```

## Data


```{r}
# Função para buscar as coordenadas dos países
# (?map_data)
mapa <- map_data("world")
```


```{r}
# Gerando o mapa
ggplot() + geom_polygon(data = mapa, aes(x=long, y = lat, group = group)) + 
  coord_fixed(1.3)

```


```{r}
# Tira o preenchimento e coloca o contorno
ggplot() + 
  geom_polygon(data = mapa, aes(x=long, y = lat, group = group), fill = NA, color = "blue") + 
  coord_fixed(1.3)
```


```{r}
# Preenchimento com uuma cor diferente
gg1 <- ggplot() + 
  geom_polygon(data = mapa, aes(x=long, y = lat, group = group), fill = "seagreen1", color = "blue") + 
  coord_fixed(1.3)
gg1
```


```{r}
# Representando os pontos no mapa (é possivel escolher por lat e lon)
# Marcando alguns pontos no mapa
# Podemos usar um shapefile ( no BR: site do IBGE)
labs <- data.frame(
  long = c(69.24140, -2.8456051),
  lat = c(-78.38995, 22.44512),
  names = c("Ponto1", "Ponto2"),
  stringsAsFactors = FALSE
) 
```


```{r}

# colocando pontos(def acima) no mapa 
gg1 + 
  geom_point(data = labs, aes(x = long, y = lat), color = "black", size = 2) +
  geom_point(data = labs, aes(x = long, y = lat), color = "red", size = 2)

```


```{r}

# Divisão por países
ggplot(data = mapa) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE)

```


Para mais exemplos com instruções para instalação dos pacotes:
rMaps 
http://rmaps.github.io


Fim
